name: Welcome
author: Shashwat
baseurl:
description: Un rincon para la comida 
github: 
twitter: https://twitter.com/maria_recetas 
facebook: http://www.facebook.com
linkedin: 
email: maria.silva1992@gmail.com 
location: 
disqus: 

##Make sure to edit the above fields, especially for disqus.


highlighter: rouge
markdown: kramdown
encoding: utf-8
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

