# Site settings
title: Maria's Recipes 
email:
description: > # this means to ignore newlines until "baseurl:"
  An Homage To The Foodie Within Me. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner: Maria Silva Fernandez
email: maria.silva1992@gmail.com
facebook_username: maria.silva.5851
twitter_username:
github_username:
address:
  - line:
  - line:
  # Feel free to add more lines here 
telephone: +33 xx xx xx xx xx
copyright:

# API settings
google_api_key:

# Build settings
markdown: kramdown
